### ISSUE TITLE
Conditionally show/hide a tab

### ISSUE THREAD

**Issue by DevanB** [meteortemplates/tabs#13]
Is there a way to conditionally (maybe based upon the value of a helper) show/hide a tab?

**Comment by jonjamz** [comment]
Sure, you'd just have to do that in the array that the tabs helper returns.

**Comment by jonjamz** [comment]
If they're on the tab that gets hidden, the lib should automatically send them to an adjacent tab that is still available.

**Comment by DevanB** [comment]
Awesome. And what about nesting tabs. Is that possible? I gave it a try, but when I click a nested tab, it seems to be trying to open one of the non-nested tabs. I made sure to define a new helper and name the nested tab a different name also.

**Comment by jonjamz** [comment]
It may be an issue with event bubbling. See this:

https://github.com/meteortemplates/tabs/blob/master/templates:tabs.coffee#L19-L20

I would experiment with `e.stopPropagation()` and see how that fares. I can add it into the library if it works, or you can submit a PR.

Thanks!

**Comment by DevanB** [comment]
Okay thanks!
