### ISSUE TITLE
File naming under Windows

### ISSUE THREAD

**Issue by NicholasSavard** [meteortemplates/tabs#15]
Please do not use colon character (```:```) in file names as this conflicts on Windows systems.

When attempting to install the package as it's current, an ```ENOENT``` error is prompted regarding ```templates:tabs.html``` not being found in the temp folder. Full error log:

```
C:\Users\myusername\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows
.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: ENOENT, open 'C:\Users\myusername\AppData\Local\Temp\tempfolder\web.browser\t
emplates:tabs.html'
    at [...]
```

Temporary solution found : 

1. Create a new folder ```templates_tabs``` with a subfolder for the version (e.g. ```2.2.1```).

2. Download the archive of the project and extract the files without colons to the version folder or simply fetch the files using git.

3. Unless git took care of it already: Create new files replacing the colons with underscores and copy their contents respectively.

4. Create a new ```isopack.json``` for the package. I won't go in details here as there are enough documentation regarding this or simply copy an ```isopack``` from another package.

5. Move the package folder to ```C:\Users\myusername\AppData\Local\.meteor\packages\```

6. Run ```meteor add templates:tabs``` and launch your application. Enjoy.

**Comment by jonjamz** [comment]
Fixing this should be as simple as forking the repo, changing the file names to not have colons, updating the file names in package.js and submitting a PR.

**Comment by gregv21v** [comment]
Has this been done. I'm still getting an error when installing the package through the "meteor add templates:tabs" command.

**Comment by jonjamz** [comment]
Should be fixed in the latest version.

**Comment by NicholasSavard** [comment]
Works great :+1:
Thanks!
