### ISSUE TITLE
activeTab causes failure to render content of tab (FlowRouter)

### ISSUE THREAD

**Issue by screaser** [meteortemplates/tabs#18]
I have a "basicTabs" interface working, and want to add "activeTab" functionality so that I can route directly into a tab.

Adding the "activeTab" parameter to the tabs container "works", except that the tab then renders completely blank. Clicking to another tab and then back to the one I made "active" then makes the content appear... but the initial render is completely blank.

Using FlowRouter for routing, in case that helps?

Some code snippets below; let me know what else I can do to help provide a reproducible example:

Diff of change to tab-container:
'-   {{#basicTabs name="tab-container" tabs=tabs}} <<< this was working 
'+  {{#basicTabs name="tab-container" tabs=tabs activeTab=activeTab}} <<< this now fails

Simplified template helper:
 activeTab: function () {
     return 'plan';
//   return FlowRouter.getParam('activetab');
 }

HTML; "plan" is a valid slug:
{{#tabContent slug='plan'}}
    {{>planSettings}}
{{/tabContent}}

**Comment by jonjamz** [comment]
See "advanced use" section of docs--I think you need to use dynamicTabs example. If that doesn't work let me know. Thanks!

**Comment by screaser** [comment]
I will try -- thanks. Sorry I'd read the docs several times and thought that just setting "activeTab" was part of basic, since info on it is within the "basic usage" section...
