### ISSUE TITLE
Support for sticky routes / controls state preservation per tab

### ISSUE THREAD

**Issue by dandv** [meteortemplates/tabs#3]
I haven't tried this package yet, but it looks very promising. Does it support stateful/sticky routes, similar to Angular's [ui-router-extras](http://christopherthielen.github.io/ui-router-extras/example/sticky/index.html)?. For the best UX, form inputs, scroll state, text selection etc. should be preserved when navigating back to a route. [iron:router doesn't yet support this](https://github.com/EventedMind/iron-router/issues/979#issuecomment-61709997). If `tabs` does, it would be a major distinguishing feature to add to the About heading of the README.

**Comment by jonjamz** [comment]
I believe it does. The mechanism for changing tabs is jQuery's `.hide()` rather than a `.remove()`.

**Comment by dandv** [comment]
Nice. A demo and mention in the README would be great.

**Comment by jonjamz** [comment]
Will add a demo very soon. For now I'm adding it to the README.

**Comment by jonjamz** [comment]
Live example link added to README.

**Comment by dandv** [comment]
:+1:
