### ISSUE TITLE
README rendered incorrectly on Atmosphere

### ISSUE THREAD

**Issue by dandv** [meteortemplates/tabs#6]
At https://atmospherejs.com/templates/tabs I see 

> Build any tabbed interface: * really easily. * with custom templates. * with router integration. * and sticky tab states.

Re-publish maybe? If that doesn't fix it, https://github.com/percolatestudio/atmosphere/issues

**Comment by jonjamz** [comment]
Yeah I just saw that too. Weird. I'll mess with it and publish an issue if I can't fix it!

**Comment by jonjamz** [comment]
Looks like I was able to fix it. Required adding an extra newline before the bullet points.

I'll post an issue anyway, because I think they really should be using Github flavored markdown...

**Comment by jonjamz** [comment]
https://github.com/percolatestudio/atmosphere/issues/336
