### ISSUE TITLE
Meteor helpers within tabContent

### ISSUE THREAD

**Issue by centinel3** [meteortemplates/tabs#7]
First, thank you for this package. This is awesome! 

I want to use this within my project, though am unsure how to leverage Meteor template helpers within the individual tabs. My thought is that I would like to move the Meteor.subscribe methods to the individual tab render functions and remove them from the iron router waitOn functions. That way I could speed up the load time a bit and not bring back all the data at once. 

Currently I'm using iron router and the waitOn: method to subscribe to a few collections. 

waitOn: function() {
      return [Meteor.subscribe('colors', this.params._id), etc.....];
    },

On the parent template, I have blocks of code that loop through the collection data to list out all the entries.

<div class="colors">
    {{#each colorsItems}}
    {{> colorsItemTpl}}
    {{/each}}
  </div>

Per your docs and so I have seen, each tab has it's own scope, which is awesome, just not sure the best way to go about leveraging meteor helpers within the tab render callback (if that is even feasible). 

Any help would be appreciated. Thanks in advance and again, thank you! -Chris

**Comment by jonjamz** [comment]
Thank you--I'm glad you like the package!

I think you'd want to put template helpers on the tabbed interface. The individual tabs should share that context. The `{{#tabContent}}` block doesn't specify any data, so in my experience it would take on the direct parent template's context.

As for subscriptions--I think the fastest way to deal with subscriptions is to decouple them from specific routes or tabs as much as possible. I never bought into `waitOn`, personally.

It's crazy how fast your app runs across routes when you don't have to wait for subscriptions each time. Same thing with tabs.

**Comment by centinel3** [comment]
Thanks for getting back with me Jon. I have tried a few ways to get helpers working and seem to be missing something. 

How would I go about adding helpers to the basicTabs context? 
- I have tried adding a property to the ReactiveTabs.createInterface function.
- I have tried it like this: Template.basicTabs.helpers({})

Regarding subscriptions, I'm all for quick as possible page loads. If your suggestion is to decouple them from tabs and routes, then where would they live if you need to reference the cursor to display data to the user? Would you move them to the individual page template controllers? If so, aren't you still making a db call every time the page loads? The difference would be that the page would load quicker initially as it wasn't waitingOn anything, though wouldn't the data then possibly not all be there initially when the user hits the page?

Thanks again and will talk with you soon. Chris

**Comment by jonjamz** [comment]
I'll have to look into this more. `Template.basicTabs.helpers` should work.

To start, I typically load subs based on whether a user is logged in. Then I get more granular from there. Usually I just paginate subscriptions and sort them in a way that makes sense. When more specific data is needed that isn't already on the client, I subscribe to that data separately and use a reactive `loading` state that gets turned off when `onReady` is fired from the sub.

General subs are usually in their own directory in `/client/subs` and feature-specific granular subs are in a feature's directory, like `client/features/[featureName]/subs.js`. This prevents me from needing to resubscribe to *everything* based on what page the user is on, and it removes the need for that logic from the scope of the router entirely.

**Comment by jonjamz** [comment]
Maybe putting the helpers on the template that contains `basicTabs`?

**Comment by centinel3** [comment]
Hey Jon,

I figured it out with your help. It was as you said, keeping the helper on the main parent context. My issue from there was scope related. I needed to get the id of the project which was on the parent context as well, though since I moved it to the tab, it was then in a child scope. I used the following to correct the scope issue.

filesItems: function() {
    return FilesCollection.find({projectId: Template.parentData(1)._id});
  },


Regarding the subscriptions, I want to wrap my head around this (as I'm still fairly new to Meteor), so please bear with me. I'm using iron router and also do a check to make sure the user is logged in. I'm dealing with (sometimes) multiple collections needed on the same page (around 5-7 tops) and figured that it would make sense to use the waitOn method that iron router has. By moving them out from the router onto a shared folder all by themselves (in the lib folder I presume?), you would gain in page oad speed? Essentially you are subscribing to all necessary collections upfront when the user logs in, then using the collection.find() on whatever pages need the data? Just want make sure that I understand that correctly. 

Thanks again Jon. The tabs are awesome and will be taking some time to hook them all up. 

Sincerely,
Chris Campbell

**Comment by katopz** [comment]
Hi @jonjamz  @centinel3 ,

I just hit this issue, Anyone have simple example for this? 
Data is there waiting outside scope and I can't find the way to make it work.

```html
        {{#tabContent slug="post"}}
            <div class="row" id="champion-messages">
                <div class="col-md-9">
                    <!-- if I move this out of scope this will work, but not in here -->
                    <div class="template-posts">
                        {{#each posts}}
                            {{> post}}
                        {{else}}
                            {{> noData}}
                        {{/each}}
                    </div>
                </div>
            </div>
        {{/tabContent}}
```

Thanks
