### ISSUE TITLE
Names and CSS Classes

### ISSUE THREAD

**Issue by ryneeverett** [meteortemplates/tabs#8]
I find the use of the word `name` in this project ambiguous. I would think `name` would refer to what is displayed on the screen, but it is also used to refer to a CSS class:

```xml
<template name="basicTabs">
  <div class="basicTabs-container {{name}}">
...
```

I wonder if it wouldn't be better to name it something else, for example:

```xml
<template name="basicTabs">
  <div class="basicTabs-container {{klass}}">
...
```

It would also be nice if there were a similar functionality in `BasicTabs` for assigning classes to `tab-item`'s, for example:

```xml
    <ul class="tabs-list">
      {{#each tabs}}
        <li class="tab-item {{klass}} {{isActiveTab slug}}">{{name}}</li>
      {{/each}}
    </ul>
```

**Comment by jonjamz** [comment]
I can add a way for you to put in custom classes, and also I think that should probably be `slug` instead of `name`.

**Comment by Kostanos** [comment]
+1

Just a simple extra parameter, will make our life easiest to write DOM tests and to assign custom styles.

**Comment by jonjamz** [comment]
Added in `v2.2.2`.
