### ISSUE TITLE
Alternative Tab Content Definition

### ISSUE THREAD

**Issue by ryneeverett** [meteortemplates/tabs#9]
The README says:

```md
      There are two ways to define content for your tabs:

      1. Wrap each tabbed section in a blank `<div></div>`.
         Sections must correspond with the order of the tabs you specified.

      2. Wrap each tabbed section in the provided block helper (RECOMMENDED!).
         `{{#tabContent slug="nameOfSlug"}} ... {{/tabContent}}`
         These can be defined in any order you like.
```

Is `1` really an option? If so, how is one supposed to "unhide" it (since the block helper is responsible for setting the `active` class that changes the `display` setting)?

--

FYI, I'm just trying to add a class to the `<section>`'s without forking, so I'd again be satisfied with:

```xml
<template name="tabContent">
  <section class="tabs-content {{klass}} {{isActiveTab slug}}" data-tab={{slug}}>
```

**Comment by jonjamz** [comment]
1 should be an option, but I wouldn't recommend it. It mostly exists for backwards compatibility.

See the code here:
https://github.com/meteortemplates/tabs/blob/master/templates:tabs.coffee#L75

I'll have to respond to your class concerns a little bit later when I have more time to dig into the code. Let's continue that discussion in your other issue.

**Comment by ryneeverett** [comment]
@jonjamz, I don't mind if you want to keep discussion in one issue, but I'd like to clarify that while I'm personally only concerned about adding custom classes at this time, the ability to use a custom definition of `#tabContent` seems of greater importance since it's not clear if it can be done without forking the entire project (which I have).

**Comment by jonjamz** [comment]
You shouldn't have to fork the project to write your own `#tabContent`. Just copy the HTML and JS from the package over for that template in your project and keep the existing helpers and add your own new stuff. The codebase of the package is really small, like ~140 LOC, and it's all just Blaze.

**Comment by ryneeverett** [comment]
Ah, good point. I hadn't realized that the `tabContent` helper was independent of the rest of the package.
